### ISSUE TITLE
Failed push actions using default repo

### ISSUE THREAD

**Issue by KevSex** [ludeeus/integration_blueprint#72]
## Version of the custom_component
Using latest `master`

## Configuration

```yaml

N/A

```

## Describe the bug
When I create a new repository from integration_blueprint using the 'Use this template' button, the new repo is created successfully however the `push` actions workflow fails.

Initially it failed due to not providing a description and missing topics however after correcting these, it passes the **Validation** job. It is however now failing at the **Run tests** and I'm unsure on how to resolve. 

See debug log below for full details.

From reading some articles online on this ImportError, this may relate to `contextfunction` being replaced by `pass_context` in Jinja2 3.0.0 however I'm not entirely sure how to resolve this as the code that refers to this import is not part of this repo.

Please advise if I'm doing something wrong or if there is additional steps required to get these Actions workflow working correctly.

Cheers

## Debug log

```text

Run pytest \
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/_pytest/config/__init__.py", line [14](https://github.com/KevSex/ha-thruk-livestatus/runs/5744002122?check_suite_focus=true#step:5:14)3, in main
    config = _prepareconfig(args, plugins)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1[17](https://github.com/KevSex/ha-thruk-livestatus/runs/5744002122?check_suite_focus=true#step:5:17)2, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytest_homeassistant_custom_component/plugins.py", line 19, in <module>
    from homeassistant import core as ha, loader, runner, util
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/homeassistant/runner.py", line 10, in <module>
    from homeassistant import bootstrap
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/homeassistant/bootstrap.py", line [18](https://github.com/KevSex/ha-thruk-livestatus/runs/5744002122?check_suite_focus=true#step:5:18), in <module>
    from homeassistant import config as conf_util, config_entries, core, loader
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/homeassistant/config.py", line 56, in <module>
    import homeassistant.helpers.config_validation as cv
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/homeassistant/helpers/config_validation.py", line 76, in <module>
    from homeassistant.helpers import (
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/homeassistant/helpers/script_variables.py", line 9, in <module>
    from . import template
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/homeassistant/helpers/template.py", line [25](https://github.com/KevSex/ha-thruk-livestatus/runs/5744002122?check_suite_focus=true#step:5:25), in <module>
    from jinja2 import contextfunction, pass_context
ImportError: cannot import name 'contextfunction' from 'jinja2' (/opt/hostedtoolcache/Python/3.8.12/x[64](https://github.com/KevSex/ha-thruk-livestatus/runs/5744002122?check_suite_focus=true#step:5:64)/lib/python3.8/site-packages/jinja2/__init__.py)
Error: Process completed with exit code 1.

```

**Comment by golles** [comment]
I've ran into the same issue, will create a PR for this

**Comment by ludeeus** [comment]
Tests was removed in <https://github.com/ludeeus/integration_blueprint/commit/15feac505d7b21e6c17e48f918fa04cf0e340a0e> ref <https://github.com/ludeeus/integration_blueprint/issues/83> so this is no longer needed 👍
